### ISSUE TITLE
layout for custom page

### ISSUE THREAD

**Issue by snowleung** [rwwaskk/linkedlist#2]
if layout section is
layout: page
the navigation not available.
but use 'layout: home' is work well.
============
also generate about/index.html with this content
---
layout: home
title: About Me
---
<header>
        <h2>About Me</h2>
</header>

what's this use for ?
https://www.leisiwo.com, using this theme.

**Comment by rwwaskk** [comment]
Hey @snowleung thanks for bringing this up. This repo def. needs more love. Feel free to make a PR. I will try to fix this ASAP, as well.

**Comment by snowleung** [comment]
@rwwaskk thank you for your reply.  i have been move to 'hexo'. 
thank you, again.
